# Generated by Django 3.1.1 on 2020-11-27 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(error_messages={'unique': 'اسم مكرر'}, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='يجب أن يكون الاسم مُكون من خمسة أحرف على الأقل'), django.core.validators.RegexValidator("[a-zA-Z\\s\\-\\']+|[\\u0621-\\u064A ]+", 'مسموح فقط بإدخال حروف عربية أو لاتينية للأسماء')])),
                ('address_gov', models.CharField(choices=[('', 'إختر محافظة'), ('Cairo', 'القاهرة'), ('Giza', 'الجيزة'), ('Alexandria', 'الأسكندرية'), ('Dakahlia', 'الدقهلية'), ('Red_Sea', 'البحر الأحمر'), ('Beheira', 'البحيرة'), ('Faiyom', 'الفيوم'), ('Gharbia', 'الغربية'), ('Ismailia', 'الإسماعلية'), ('Munofia', 'المنوفية'), ('Minya', 'المنيا'), ('Qalubiya', 'القليوبية'), ('New_Valley', 'الوادي الجديد'), ('Suez', 'السويس'), ('Aswan', 'أسوان'), ('Asyut', 'أسيوط'), ('Beni_Suef', 'بني سويف'), ('Port_Said', 'بورسعيد'), ('Damietta', 'دمياط'), ('Sharqia', 'الشرقية'), ('South_Sinai', 'جنوب سيناء'), ('Kafr_El_Sheikh', 'كفر الشيخ'), ('Matroh', 'مطروح'), ('Luxor', 'الأقصر'), ('Qena', 'قنا'), ('North_Sinai', 'شمال سيناء'), ('Sohag', 'سوهاج')], max_length=20)),
                ('address_street', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5, message='يجب أن يكون العنوان مُكون من خمسة أحرف على الأقل')])),
                ('email', models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z0-9_\\.-]+\\@[a-zA-Z]+[a-zA-Z0-9]+\\.[a-z]+(\\.[a-z]+)?', 'ادخل عنوان بريد إليكتروني صحيح')], verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': 'اسم مستخدم مكرر'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(6, message='يجب أن يكون اسم المستحدم مُكون من ستة أحرف على الأقل'), django.core.validators.RegexValidator('[a-zA-Z][a-zA-Z0-9_\\.-]+', 'ادخل اسم مستخدم صحيح يبدأ بحرف ويمكن أن يحتوي على أرقام أو شرطة سفلية _ أو شرطة - أو نقطة')])),
                ('is_center', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(error_messages={'unique': 'رقم هاتف أو جوال مكرر'}, max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(9, message='ادخل رقم هاتف مكون من تسعة أرقام على الأقل'), django.core.validators.RegexValidator('[0][0-9]+', 'ادخل رقم هاتف أو جوال صحيح يبدأ بصفر')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Phone numbers',
            },
        ),
    ]
