# Generated by Django 3.1.1 on 2020-12-05 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20201205_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='userPhones',
            field=models.CharField(default=0, max_length=15, validators=[django.core.validators.MinLengthValidator(9, message='ادخل رقم هاتف مكون من تسعة أرقام على الأقل'), django.core.validators.RegexValidator('[0][0-9]+', 'ادخل رقم هاتف أو جوال صحيح يبدأ بصفر')]),
            preserve_default=False,
        ),
    ]
