# Generated by Django 3.1.1 on 2020-12-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20201205_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
