# Generated by Django 3.1.1 on 2020-12-19 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_customuser_is_full'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_full',
        ),
    ]
